name: Summarize Issue

on:
  issue_comment:
    types: [created]

jobs:
  summarize_issue:
    if: startsWith(github.event.comment.body, '/summarize-issue')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Cache poetry virtualenv
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false
      - if: ${{steps.cache.outputs.cache-hit != 'true' }}
        name: Install Python library
        run: |
          poetry install --no-interaction

      - name: Run summarizer
        run: poetry run python src/main.py "${{ github.event.repository.full_name }}" "${{ github.event.issue.number }}" "${{ github.event.comment.id }}" "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
